In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[6,7,9]])
print(a,"\n\n",b)


[1 2 3] 

 [[1 2 3]
 [6 7 9]]


In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
print(np.arange(0,10,2))
print(np.arange(10,45,5))

[0 2 4 6 8]
[10 15 20 25 30 35 40]


In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
print(a[2])

3


In [10]:
print(a[0:2])

[1 2]


In [11]:
matrix = np.array([[1,2,3],[9,8,7]])
print(matrix)

[[1 2 3]
 [9 8 7]]


In [12]:
print(matrix[1,1])
print(matrix[0,2])

8
3


In [13]:
print(matrix[:,2])

[3 7]


In [14]:
print(matrix[1,:])

[9 8 7]


In [15]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [16]:
print(arr.reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [17]:
print(arr.reshape(3,2))

[[0 1]
 [2 3]
 [4 5]]


In [18]:

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

In [19]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
np.split(arr, 3)


[array([0, 1]), array([2, 3]), array([4, 5])]

In [24]:
bc = np.array([1,2,3])
b = 3
print(bc+b)

[4 5 6]


In [29]:
bc2 = np.array([[1,2,3],[7,8,9]])
b1 = [2,3,5]
print(bc2+b1)

[[ 3  5  8]
 [ 9 11 14]]


In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)
print(b**a)

[ 4 10 18]
[  4  25 216]


In [34]:
a.sum()

np.int64(6)

In [35]:
a.mean()

np.float64(2.0)

In [36]:
a.max(),a.min()

(np.int64(3), np.int64(1))

In [37]:
a.std()

np.float64(0.816496580927726)

In [39]:
np.sqrt(a), np.exp(a), np.sin(a), np.cos(a), np.log(a)

(array([1.        , 1.41421356, 1.73205081]),
 array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([0.84147098, 0.90929743, 0.14112001]),
 array([ 0.54030231, -0.41614684, -0.9899925 ]),
 array([0.        , 0.69314718, 1.09861229]))

In [41]:
from numpy.linalg import *

In [42]:
np.dot(a,b)

np.int64(32)

In [43]:
np.matmul(a,b)

np.int64(32)

In [48]:
ab = np.array([[1,2],[3,4]])

In [51]:
a.T,inv(ab) , det(ab)

(array([1, 2, 3]),
 array([[-2. ,  1. ],
        [ 1.5, -0.5]]),
 np.float64(-2.0000000000000004))

In [53]:
eig(ab)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [57]:
np.random.seed(42) # reproducibility

In [60]:
np.random.rand(3)

array([0.05808361, 0.86617615, 0.60111501])

In [61]:
np.random.randn(3)

array([-0.58087813, -0.52516981, -0.57138017])

In [63]:
np.random.randint(1, 10, 7)

array([4, 9, 3, 5, 3, 7, 5])

In [64]:
np.random.normal(loc=0, scale=1, size=5)

array([-0.92408284, -0.29339915, -0.02983857,  0.09512578,  0.66465434])

In [65]:
np.random.binomial(n=10, p=0.5, size=5)

array([5, 2, 4, 4, 6])

In [66]:
np.random.poisson(lam=3, size=5)

array([3, 3, 1, 5, 8])

In [73]:
res = []
for i in a:
  res.append(i**2)
print(res)
#slow

[np.int64(1), np.int64(4), np.int64(9)]


In [72]:
res = a**2
print(res)

[1 4 9]


In [74]:
from scipy.sparse import csr_matrix

In [75]:
sparse = csr_matrix(np.eye(1000))
print(sparse)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1000 stored elements and shape (1000, 1000)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
  (6, 6)	1.0
  (7, 7)	1.0
  (8, 8)	1.0
  (9, 9)	1.0
  (10, 10)	1.0
  (11, 11)	1.0
  (12, 12)	1.0
  (13, 13)	1.0
  (14, 14)	1.0
  (15, 15)	1.0
  (16, 16)	1.0
  (17, 17)	1.0
  (18, 18)	1.0
  (19, 19)	1.0
  (20, 20)	1.0
  (21, 21)	1.0
  (22, 22)	1.0
  (23, 23)	1.0
  (24, 24)	1.0
  :	:
  (975, 975)	1.0
  (976, 976)	1.0
  (977, 977)	1.0
  (978, 978)	1.0
  (979, 979)	1.0
  (980, 980)	1.0
  (981, 981)	1.0
  (982, 982)	1.0
  (983, 983)	1.0
  (984, 984)	1.0
  (985, 985)	1.0
  (986, 986)	1.0
  (987, 987)	1.0
  (988, 988)	1.0
  (989, 989)	1.0
  (990, 990)	1.0
  (991, 991)	1.0
  (992, 992)	1.0
  (993, 993)	1.0
  (994, 994)	1.0
  (995, 995)	1.0
  (996, 996)	1.0
  (997, 997)	1.0
  (998, 998)	1.0
  (999, 999)	1.0


In [79]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr_reshaped = arr.reshape((2, 3))